name: Doc to PDF

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: README.md
          output_dir: pdfs
          build_html: false

      - uses: actions/upload-artifact@v1
        with:
          name: README.pdf
          path: pdfs/README.pdf
